### ISSUE TITLE
JWT Secret is generated using os.getrandom

### ISSUE THREAD

**Issue by ben9583** [ocf/api#40]
Not sure if this is actually how ocfapi works, but I've been encountering a bug on ocfstatic that I've been trying to deal with for the past 2 weeks and here is my theory:

We use Kubernetes for the api which means there are multiple instances of the API running. One of the jobs of the api is to sign JWTs for `ocfapi_calnet`, which is needed in cases of, for example, resetting passwords. However, these secrets (when not on debug mode) are generated using `os.getrandom(32).hex`, which is problematic because it means different instances of ocfapi running on kubernetes have different secrets. This means it's basically a lottery as to whether or not you get the same instance running the api you used when signing the JWT vs verifying the JWT.

We need to change it so these instances all rely on the same secret. I could be wrong about my understanding of how this all runs but I feel pretty confident about it because this api only works some of the time with the same `curl` request.

[Here is the code](https://github.com/ocf/api/blob/master/app/utils/calnet.py#L18) that I'm talking about for reference.

**Comment by ben9583** [comment]
Not really sure what's the best solution here cause we obv don't want the secret on the repo but we need consistency. Maybe we can add a build step that randomly generates the secret as a file? Idk how kubernetes works and if there's a way to share secrets like this.

**Comment by Kalissaac** [comment]
From what I can tell, there's only one pod running and the deployment should be set to only have 1 replica. Do you have a way to reproduce this that I can test? I tried creating a token and using it on the api docs page and it was working fine for me.

If we need, we can just create a jwt secret and throw it in a kube secret and then load that in with an environment variable, and that should solve the problem.

**Comment by ben9583** [comment]
I was just running:
```sh
 curl 'https://api.ocf.berkeley.edu/account/reset_password' -X POST -H 'Accept: application/json' 'Authorization: Bearer [TOKEN]' -H 'Content-Type: application/json' --data-raw '{"account":"bplate","new_password":"."}'
```
Trying to get a bad password error, occasionally I do but usually it's `"malformed jwt"`

**Comment by Kalissaac** [comment]
turns out it spins up workers, which each generate their own secret :(
