### ISSUE TITLE
Create Announcements Repo

### ISSUE THREAD

**Issue by ben9583** [ocf/api#48]
We'll be creating a GitHub repository for our announcements, which should contain markdown files for announcements. The idea is that OCF staff can create announcements by uploading a markdown file, which our backend tools will be able to retrieve to display using our API.

- [x] Create the repository (link here when done)
- [x] Define schema for repository (how it is structured)
- [x] Define schema for markdown files

**Comment by vicshi06** [comment]
```bash
routes/
├── account/
│   ├── hosting/
│   │   ├── __init__.py
│   │   ├── app.py
│   │   ├── mail.py
│   │   └── vhost.py
│   ├── quota/
│   │   ├── __init.py
│   │   └── paper.py
│   ├── __init__.py
│   ├── commands.py
│   ├── me.py
│   ├── register.py
│   └── reset_password.py
├── auth/
│   ├── __init__.py
│   └── calnet.py  
├── lab/
│   ├── __init__.py
│   ├── desktops.py
│   ├── hours.py
│   ├── session_tracking.py
│   └── users.py
├── announcement/
│   └── __init__.py
├── __init__.py
├── announce.py
├── meetings.py
├── shorturls.py
└── staff_hours.py
```

**Comment by ben9583** [comment]
Looking good! Some comments I have:

- The name of the markdown file uses a different date format from the format in the announcement file itself. I think YYYY-MM-DD is generally better, but in any case, this would make creating multiple announcements on the same day a bit complicated. Maybe for the ID/filename, we can just count up?
- Ideally it would be nice to have a short blurb about the announcement that we could show on the list of announcements. I think it may be good to have this as a metadata entry along with the other 4 items you have so far.
- Maybe for assets, we can group things based on announcement, rather than asset type? For instance, for a given announcement `42.md`, we'd have a directory in `assets/42` where images, videos, etc. would go. This way, it would be easier to modify the assets of a given announcement, as the editor would just go into that announcement's respective asset directory.

Let me know what you think about these suggestions. Other that that, I think this is great!

**Comment by vicshi06** [comment]
- so we do `20020101-00.md` for the first announcement of that day and `20020101-01.md` for the second one? 


## Schema for repository:
```bash
announcement/
├── 20020101-00.md
├── 20020101-01.md
├── 20020102-00.md
└── ...
assets/
├── 20020101-00/
        ├──images/
                └── ...
        ├──videos/
                └── ...
       └── ...
├── 20020101-01/
        ├──images/
                └── ..
        ├──videos/
                └── ...
        └── ...
├── 20020102-00/
        ├──images/
                └── ...
        ├──videos/
                └── ...
        └── ...
└── ...
```

## Schema for announcement:

```markdown
---
title: "Title of the Announcement"
date: YYYY-MM-DD
author: Author's Name
tags: [tag1, tag2, tag3]
summary: short summary of the announcement 
---

# Title of the Announcement

## Summary

- Summary of the announcement.

## Detail

- Detail description of the announcement.

## Contacts

- Name: Contact Person
- Email: contact@example.com
- Phone: (123) 456-7890
```

**Comment by ben9583** [comment]
I wonder if it may be good to just count up in the filename, like `0.md`, `1.md`, `2.md`, etc.

We can get the date from the metadata anyhow

**Comment by vicshi06** [comment]
From the readability standpoint, having the complete date might make more sense. or we can do something like `2002-01-01/01.md`.

**Comment by ben9583** [comment]
Hmm, ok, I guess it wouldn't affect sorting by title. Let's stick with the full name (`2002-01-01-00.md`)

**Comment by vicshi06** [comment]
@ben9583 If you think this is completed, can you close the issue? I don't want to do it since i am not the creator of the issue. Thanks Ben.

**Comment by ben9583** [comment]
Yep, looks all good now
